onboarding = false

[terminal]
default_shell = "fish"

[keys]
prefix = "ctrl+f"

goto = "prefix+g"
detach = "prefix+q"
copy_mode = "prefix+c"

new_tab = "prefix+enter"
rename_tab = "prefix+r"
previous_tab = ["prefix+u", "prefix+ctrl+u"]
next_tab = ["prefix+i", "prefix+ctrl+i"]

new_workspace = "prefix+shift+enter"
rename_workspace = "prefix+shift+r"
previous_workspace = ["prefix+o", "prefix+ctrl+o"]
next_workspace = ["prefix+y", "prefix+ctrl+y"]

split_horizontal = "prefix+ctrl+,"
split_vertical = "prefix+ctrl+."

focus_agent = "prefix+1..9"

[[keys.command]]
key = "prefix+t"
type = "popup"
command = "exec \"${SHELL:-sh}\""
description = "open scratch terminal"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+m"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+d"
type = "popup"
command = "lazydocker"
description = "run lazydocker"
width = "90%"
height = "90%"

[[keys.command]]
key = "prefix+s"
type = "popup"
command = "spf"
description = "run superfile"
width = "90%"
height = "90%"

[ui]
show_agent_labels_on_pane_borders = true

[ui.sound]
enabled = false

[theme]
name = "tokyo-night"
auto_switch = false
